# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2c202e64883d0b84a1fd955faaefac036c642d93bf0a2347e4057766b9c5abbcbf52211ef46cbf08ccb152e3739c949b1a9d1ba4db48630bb1bb5054e587703

test:
  secret_key_base: f3f9f02ff6eabc814b56a00e7d262d2274c918dbbee7858cea6c68f8c1c3623eb0bd6e693128cb14bee31073de17421a217c265b0ec443a389c523d0d96ce257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
